### PR TITLE
Feature/positioning element

### PR DESCRIPTION
**Pull request by dbucki**
Add custom positioning element

### CODE REVIEW

**Comment by SimonSteinberger** [comment]
Can you give an example of what this feature could be used for? I believe you can get left and width from the input element itself via jQuery without changes in the plugin.

**Comment by dbucki** [comment]
zrzut ekranu 2015-07-08 o 17 13 55

I produce at this point mobile webapplication, and my input (red) has a smaller width than the whole container (yellow). That's why I needed to set position relative to another element.

**Comment by SimonSteinberger** [comment]
I guess, that's a rather rare scenario. Let's see if others join in and if they do, we can include these changes in the plugin code base.

**Comment by dbucki** [comment]
Ok, I am waiting ;)

**Pull request closed without merging**
