### PR TITLE
Ignore additional keystrokes HOME(36), END(35), CTRL(17)

### PR DESCRIPTION
**Pull request by beauholland**
Firing events when not required using the following key combinations:

SHIFT + HOME ... highlighting text
SHIFT + END ... highlighting text
CTRL + A ... select all text

Added additional key filtering to keyup.autocomplete check

### CODE REVIEW

**Comment by SimonSteinberger** [comment]
The keyup event still gets fired -  not really seeing what's the advantage here. The source function for the autocompleter isn't called without value change of the input field. That's what the `if (val != that.last_val) {` statement is for.

**Comment by beauholland** [comment]
Good point - Got an AJAX query as source which seems to fire when I keyup HOME, END, CTRL, regardless. Might be something I am doing on my end. I'll put something simple together to try and reproduce.

**Comment by SimonSteinberger** [comment]
Hm, strange, it shouldn't fire then. I don't see the requests on my test system on Pos1, End, etc.. Let me know if you find out more  about this, please :+1:

**Comment by beauholland** [comment]
Replicated the problem here: http://jsfiddle.net/hollandbeau/0xqsdasg/4/
I am setting the value of the input field to be what was selected therefore the previous val and val will be different.

**Comment by SimonSteinberger** [comment]
I see - I guess, including the few extra key does solve the issue more or less. There could be other problems when setting the input field's value manually. Well, adding those 4 keys as an exception certainly doesn't blow up the code a lot. So, if that solves the problem for you, it's fine.

**Comment by SimonSteinberger** [comment]
I believe #17 won't work as expected. That's the keycode for pressing CTRL only. CTRL+A is different or would require checking for `(e.ctrlKey && e.which == 65)`, but aren't there lots of other such CTRL key combinations? Shouldn't we - for simplicity - only add #35 and #36 as exceptions?

**Comment by beauholland** [comment]
Yep - #35, #36

**Pull request closed without merging**
